/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class solutions_cloudarchitects_vsockj_VSockImpl */

#ifndef _Included_solutions_cloudarchitects_vsockj_VSockImpl
#define _Included_solutions_cloudarchitects_vsockj_VSockImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     solutions_cloudarchitects_vsockj_VSockImpl
 * Method:    socketCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_solutions_cloudarchitects_vsockj_VSockImpl_socketCreate
  (JNIEnv *, jobject);

/*
 * Class:     solutions_cloudarchitects_vsockj_VSockImpl
 * Method:    connect
 * Signature: (Lsolutions/cloudarchitects/vsockj/VSockAddress;)V
 */
JNIEXPORT void JNICALL Java_solutions_cloudarchitects_vsockj_VSockImpl_connect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     solutions_cloudarchitects_vsockj_VSockImpl
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_solutions_cloudarchitects_vsockj_VSockImpl_close
  (JNIEnv *, jobject);

/*
 * Class:     solutions_cloudarchitects_vsockj_VSockImpl
 * Method:    write
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_solutions_cloudarchitects_vsockj_VSockImpl_write
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     solutions_cloudarchitects_vsockj_VSockImpl
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_solutions_cloudarchitects_vsockj_VSockImpl_read
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     solutions_cloudarchitects_vsockj_VSockImpl
 * Method:    bind
 * Signature: (Lsolutions/cloudarchitects/vsockj/VSockAddress;)V
 */
JNIEXPORT void JNICALL Java_solutions_cloudarchitects_vsockj_VSockImpl_bind
  (JNIEnv *, jobject, jobject);

/*
 * Class:     solutions_cloudarchitects_vsockj_VSockImpl
 * Method:    listen
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_solutions_cloudarchitects_vsockj_VSockImpl_listen
  (JNIEnv *, jobject, jint);

/*
 * Class:     solutions_cloudarchitects_vsockj_VSockImpl
 * Method:    accept
 * Signature: (Lsolutions/cloudarchitects/vsockj/VSockImpl;)V
 */
JNIEXPORT void JNICALL Java_solutions_cloudarchitects_vsockj_VSockImpl_accept
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
