/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class solutions_cloudarchitects_vsockj_VSockSocketServerJNI */

#ifndef _Included_solutions_cloudarchitects_vsockj_VSockSocketServerJNI
#define _Included_solutions_cloudarchitects_vsockj_VSockSocketServerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     solutions_cloudarchitects_vsockj_VSockSocketServerJNI
 * Method:    connect
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_solutions_cloudarchitects_vsockj_VSockSocketServerJNI_connect
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
